mylist = ["Pruthviraj", "Aditya", "Vedant","Michael"]
print("Now 'Kartik' would be appended")
mylist.append("Kartik")
print(mylist)
print("Reversed list :")
mylist.reverse()
print(mylist)
print("Removing or poping the 4th element")
mylist.pop(3)
print(mylist)
print("The length of the list is : ")
print(len(mylist)) 